### ISSUE TITLE
Ошибка "На этом сайте переводы недоступны"

### ISSUE THREAD

**Issue by azzy-kikoz** [yoomoney/cms-opencart3#101]
Здравствуйте. Снова вопрос есть.

На опенкарте (3.0.2.0) заведены две витрины с разными доменными именами. Они доступны со своим набором товаров, местами пересекающимся. В админке настраиваем ЮMoney (не ЮKassa). 
В поле RedirectURL указано доменное имя  **первой** витрины.  

При оплате заказа на **первой** витрине происходит проброс на адрес https://yoomoney.ru/quickpay/confirm.xml и ошибка "На этом сайте переводы недоступны
Если вы — владелец формы (кнопки), напишите службе поддержки ЮMoney. В сообщении укажите полный адрес сайта, на котором стоит форма (кнопка)."

При оплате на **второй** витрине: все отлично. Идет проброс на https://yoomoney.ru/transfer/quickpay?requestId= и есть возможность оплатить.

В чем может быть проблема ? Техподдержка ЮМоней ничего внятного сказать не может.

**Comment by ostulov** [comment]
Добрый день!

Необходимо проверить данные, которые от Вас передаются в момент оплаты. Для этого напишите, пожалуйста, адрес сайта.
Если Вы не хотите здесь раскрывать адрес сайта, пришлите его письмом на почту cms@yoomoney.ru

**Comment by azzy-kikoz** [comment]
Здравствуйте.
Отправил информацию Вам на почту. Но пока так и нет ответа. Могу продублировать, если потерялось.

**Comment by ostulov** [comment]
Добрый день!

Ваше сообщение получено, ожидайте ответного письма на почту.

**Comment by ostulov** [comment]
Со стороны модуля технических проблем в приеме оплаты нет.
Ошибка может возникать из-за индивидуальных особенностей сайта.  Для уточнения подробностей Ваше обращение передано в службу поддержки ЮMoney. Ожидайте ответа на почту.

**Comment by azzy-kikoz** [comment]
Спасибо за информацию. Подтверждаю - проблема не со стороны модуля, а со стороны кошелька.
